### PR TITLE
Change Kvaser_Mat to a function

### PR DESCRIPTION
**Pull request by aaronbeekay**
Changes Kvaser_Mat into a function, Kvaser_Mat( MATFILE_Name ), which returns the variables that Kvaser_Mat set originally

### CODE REVIEW

**Comment by aaronbeekay** [comment]
@lordnathan0 @sharrington93 will this break any of your workflow? It makes the Kvaser_Mat function easier to use.

**Comment by lordnathan0** [comment]
@aaronbeekay @sharrington93 
This does break the current workflow because the other scripts take in a converted mat file and this script does not create one.

**Comment by sharrington93** [comment]
@aaronbeekay @lordnathan0 A solution would be taking in an additional input that is the file name of the converted mat file. Then just store the data in that file along with returning the map and headers if that's useful for you Aaron.

**Comment by aaronbeekay** [comment]
@lordnathan0 @sharrington93 I added another script, `save_kvaser_mat.m`, that behaves the same way that the old script used to -- for any workflow that used the output MATfile, `save_kvaser_mat` can replace `Kvaser_Mat` seamlessly.

This an acceptable solution?

**Comment by lordnathan0** [comment]
Yes that works for me

**Comment by sharrington93** [comment]
Works for me then too. Merging.

**Pull request merged**
